'PROJECT_ID': 'mars-snacking-dce'
'REGION': 'us-central1'
'LOCATION': 'us'
'DSNAME': 'mars-ai-innovation-datastore_1713291787164'
'DENAME': 'mars-innovation-search_1713363757627'

'WEBUSER': 'demo_user'
'WEBPASS': 'demo_pass'