'PROJECT_ID': 'your_project_id'
'REGION': 'us-central1'
'LOCATION': 'us'
'DSNAME': 'agent_builder_datastore_name'
'DENAME': 'agent_builder_engine_name'

'WEBUSER': 'set_a_username'
'WEBPASS': 'set_a_password'