'PROJECT_ID': 'YOUR_PROJECT_ID' # The name of your GCP Project
'REGION': 'us-central1' # Enter your associated region 
'LOCATION': 'global' # Setting can be us or global
'DSNAME': 'YOUR_DATASTORE_NAME' # The name of the Vertex AI Search data store
'DENAME': 'YOUR_AI_SEARCH_ENGINE_ID' # The name of the Vertex AI Search engine app

# Setting if using basic authentication 
'WEBUSER': 'user' # The username you want to use
'WEBPASS': 'pass' # The password you want to use